### ISSUE TITLE
Empty payload results in divide by zero and server crash

### ISSUE THREAD

**Issue by gerritvd** [huggingface/text-embeddings-inference#135] opened 2024-01-22 23:29 UTC
In v0.6 we get:

```
thread 'tokio-runtime-worker' panicked at /usr/src/router/src/http/server.rs:541:42: 
 attempt to divide by zero 
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```

See https://github.com/huggingface/text-embeddings-inference/blob/282812743444c33f9e5f4f3681dbbe2472fd651e/router/src/http/server.rs#L541

The client shouldn't be sending empty payloads, but an empty request should also not result in a crashing server.

**Comment by OlivierDehaene** [comment] 2024-01-23 09:30
Duplicate of #91

**Comment by OlivierDehaene** [comment] 2024-01-23 09:31
Duplicate of #133

**Closed by OlivierDehaene** 2024-01-23 09:30 UTC
