### ISSUE TITLE
Support for zero-shot classification models

### ISSUE THREAD

**Issue by delibae** [huggingface/text-embeddings-inference#238] opened 2024-04-13 13:44 UTC
### Model description

The request is for the implementation of zero-shot classification models, with a specific emphasis on models like facebook/bart-large-mnli(or MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli). The functionality of these models would be similar to that of rerank models or sentiment analysis models

[bart-large-mnli huggingface](https://huggingface.co/facebook/bart-large-mnli)
[MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli huggingface](https://huggingface.co/MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by matt1398** [comment] 2024-04-13 14:10
Excited to see zero-shot classification land in TEI! 🎉

**Comment by OlivierDehaene** [comment] 2024-04-15 09:27
Noted.
Duplicate of #221.

**Closed** 2024-04-15 09:27 UTC
